version: "3"
services:
  #nombre del servicio
  ditdaelasticctrl:
    hostname: ditda-elastic-ctrl
    container_name: ditdaelasticctrl
    restart: always
    build: .    
    #puertos
    ports:
      - "5003:5003"
    networks:
      - core_ditdanet
  
networks:
  core_ditdanet:
    external: true

