version: "3"
services:
  #nombre del servicio
  sia_busqueda:
    hostname: sia_busqueda
    container_name: sia_busqueda
    restart: always
    build: .    
    #puertos
    ports:
      - "5003:5003"
    networks:
      - siaa_ctrl_siaa_net
  
networks:
  siaa_ctrl_siaa_net:
    external: true

